version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - Shopify/platform-dev-tools-education
  ignore:
  - dependency-name: "@shopify/polaris"
    versions:
    - 6.0.1
    - 6.1.0
    - 6.2.0
    - 6.2.1
    - 6.2.2
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@shopify/app-bridge-react"
    versions:
    - 1.28.0
    - 1.29.0
    - 2.0.1
  - dependency-name: "@shopify/app-bridge"
    versions:
    - 1.28.0
    - 1.29.0
    - 2.0.1
  - dependency-name: "@shopify/koa-shopify-auth"
    versions:
    - 3.2.0
    - 4.0.0
    - 4.0.1
    - 4.0.2
    - 4.0.3
    - 4.1.0
    - 4.1.1
    - 4.1.2
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
    - 7.23.0
    - 7.23.1
  - dependency-name: "@shopify/koa-shopify-webhooks"
    versions:
    - 2.6.0
    - 2.6.1
    - 2.6.2
    - 2.6.3
  - dependency-name: "@shopify/koa-shopify-graphql-proxy"
    versions:
    - 4.1.0
    - 4.1.1
    - 4.1.2
    - 4.1.3
  - dependency-name: urijs
    versions:
    - 1.19.5
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
